### ISSUE TITLE
Come up with a better name for this package

### ISSUE THREAD

**Issue by PietrH** [inbo/iassetR#11]
This package is more general than just vespa-watch, it'll work just as well for other domains on iAsset. And in fact, we are planning to use it for our other project on our domain as well. 

I'm open to any suggestions!

**Comment by SanderDevisscher** [comment]
Some suggestions from perplexity.ai:

- iassetR: This name follows the convention of adding an "R" to indicate that it is an R package, and it is short and easy to remember.
- assetR: This name is similar to the previous suggestion but without the "i" at the beginning, which could make it easier to type.
- admiralR: This name is inspired by the existing "ADaM in R Asset Library" package listed in the search results [2](https://cran.r-project.org/web/packages/available_packages_by_name.html)
. It is short and memorable, and the "R" at the end indicates that it is an R package.
- accessAPI: This name is more descriptive and straightforward, indicating that the package is used for accessing an API. It is also short and easy to remember.

**Comment by PietrH** [comment]
Suggestions by OSCIBIO:

- riasset
- riAsset

> Is this a package which will contains wrappers around iAsset API? Than something like `riAsset`? in analogy with `rgbif` and `pygbif`
> or `riasset`

- `iAsset`

**Comment by PietrH** [comment]
> Some suggestions from perplexity.ai:
> 
>     * iassetR: This name follows the convention of adding an "R" to indicate that it is an R package, and it is short and easy to remember.
> 
>     * assetR: This name is similar to the previous suggestion but without the "i" at the beginning, which could make it easier to type.
> 
>     * admiralR: This name is inspired by the existing "ADaM in R Asset Library" package listed in the search results [2](https://cran.r-project.org/web/packages/available_packages_by_name.html)
>       . It is short and memorable, and the "R" at the end indicates that it is an R package.
> 
>     * accessAPI: This name is more descriptive and straightforward, indicating that the package is used for accessing an API. It is also short and easy to remember.

I just checked, and they are all available, except `assetR`.  So I'm afraid that one is out. 

I prefer a name that has a clear name to iAsset, I quite like the feel of `library(iAsset)` , and the repo can then be called inbo/r-iasset to make clear it's the r library.

**Comment by SanderDevisscher** [comment]
<div id="choices">
  <div class="choice">
    <div class="result">
      <div class="bar" data-choice="1"></div>
    </div>
    <div class="label">
      <p>iassetR</p>
      <button data-choice="1">Vote</button>
    </div>
  </div>
  <div class="choice">
    <div class="result">
      <div class="bar" data-choice="2"></div>
    </div>
    <div class="label">
      <p>iAsset</p>
      <button data-choice="2">Vote</button>
    </div>
  </div>
  <div class="choice">
    <div class="result">
      <div class="bar" data-choice="3"></div>
    </div>
    <div class="label">
      <p>riAsset</p>
      <button data-choice="3">Vote</button>
    </div>
  </div>
</div>

**Comment by SanderDevisscher** [comment]
I prefer `iassetR`

**Comment by PietrH** [comment]
I'm ok with `iassetR`, lets switch it up next week

**Comment by SanderDevisscher** [comment]
lets do it

**Comment by PietrH** [comment]
Alright, I'll get to it

**Comment by PietrH** [comment]
Renaming a package is notorious for causing issues, so we'll need to check thoroughly.

**Comment by PietrH** [comment]
https://cran.r-project.org/web/packages/changer/readme/README.html
