### ISSUE TITLE
Create citation.cff

### ISSUE THREAD

**Issue by PietrH** [inbo/iassetR#29]
Not very difficult with `cffr::cff_write()` but I'd prefer a solution that will automatically update the citation.cff with every release

**Comment by dieghernan** [comment]
Maybe use https://docs.ropensci.org/cffr/reference/cff_gha_update.html

Creates a GitHub Action that updates the `CITATION.cff` file after some events:

> This function would install a GitHub Action on your repo. The action will update your CITATION.cff when any of these events occur:
> - You publish a new release of the package.
> - Your DESCRIPTION or inst/CITATION are modified.
> - The action can be run also manually.


That is the default configuration, see example action for more details and customisations: https://github.com/ropensci/cffr/blob/main/.github/workflows/update-citation-cff.yaml
