### ISSUE TITLE
cleanup hardcoded inputs

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/iassetR#5]
Currently some functions contain hardcoded inputs these should be removed

**Comment by PietrH** [comment]
We currently also use a lot of vespa-watch related terms in the examples, I think this is ok for now as the scope is mainly people using the package for vespa-watch. But we might want to keep an eye for the sake of RIPARIAS or external users.

**Comment by SanderDevisscher** [comment]
> We currently also use a lot of vespa-watch related terms in the examples, I think this is ok for now as the scope is mainly people using the package for vespa-watch. But we might want to keep an eye for the sake of RIPARIAS or external users.

I agree
